config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'lists#index'
  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, :list, presence: true
  validates_uniqueness_of :movie_id, scope: :list_id
  validates_length_of :comment, minimum: 6, allow_blank: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, dependent: :destroy, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # Action pour afficher toutes les listes
  def index
    @lists = List.all
  end

  # Action pour afficher le formulaire de création d'une nouvelle liste
  def new
    @movies = Movie.all
    @list = List.new
  end

  # Action pour créer une nouvelle liste
  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to lists_path, notice: 'Liste créée avec succès.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # Action pour afficher les détails d'une liste spécifique
  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end


  private

  # Méthode privée pour définir les paramètres autorisés lors de la création d'une liste
  def list_params
    params.require(:list).permit(:name, movie_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Watch-List</h1>
<% @lists.each do |list| %>
<div class = "btn btn-light" >
<%= link_to list.name, list_path(list)  %></div>
<% end %>
<div class = "btn btn-success" p-3><%= link_to "Create a list", new_list_path%></div>

app/views/lists/new.html.erb
<h1>Create a New List</h1>

<%= form_with(model: @list, url: lists_path, method: "post") do |form| %>
  <div>
    <%= form.label :name, "List Name" %>
    <%= form.text_field :name %>
  </div>

<div class="container">
  <h2>Sélectionnez des films à ajouter à la liste</h2>
  <div class="row justify-content-start">
    <% @movies.each do |movie| %>
      <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
        <div class="card text-center">
         <label> <%= image_tag movie.poster_url, alt: movie.title, class: "card-img-top", width: 200 %>
          <div class="card-body">
            <%= movie.title %>
          </div>
          <div class="card-footer">
            <%= form.check_box :movie_ids, { multiple: true }, movie.id, nil %>
          </div>
           </label>
        </div>
      </div>
    <% end %>
  </div>

  <div class="text-center">
    <%= form.submit "Create List", class: "btn btn-primary m-3" %>
    </div>
  </div>
<div class="mb-3"></div>
</div>

<% end %>

app/views/lists/show.html.erb
<div class="container">
<h1><div class = "card text-center" d-flex><%= @list.name %></div></h1>
  <div class="row justify-content-start">
<% @movies.each do |movie| %>
      <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
        <div class="card text-center">
             <%= image_tag movie.poster_url, alt: movie.title, class: "card-img-top", width: 200 %>
          <div class="card-body">
            <%= movie.title %>
          </div>
          <div class="card-footer">
          </div>
        </div>
      </div>
    <% end %>
  <%= link_to 'Delete',
  list_path(@list),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"}
  %>
</div>
</div>